site_name: Teste do Comparador de Preços
nav:
  - Bem vindo: index.md
  - Manual de uso: instrucoes.md
  - Testando e reportando: teste.md
  - Checklist detalhado: checklist.md
theme:
  logo: assets/icon.png
  favicon: assets/icon.png
  name: material
  features:
    - navigation.tabs
    - navigation.tabs.sticky
  palette:
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: deep purple
      accent: orange

    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: deep purple
      accent: blue grey
  font:
    text: Montserrat Alternates
    code: Red Hat Mono

extra_css:
      - styles/extra.css

markdown_extensions:
  - abbr
  - attr_list
  - footnotes
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - md_in_html
  - pymdownx.blocks.caption
  - pymdownx.tabbed:
      alternate_style: true
